# Generated by Django 4.2.9 on 2024-01-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_link', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
