# Generated by Django 4.2.9 on 2024-01-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_link', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='data_course',
            new_name='data_create',
        ),
    ]
