# Generated by Django 4.2.9 on 2024-01-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_link', '0002_rename_contacts_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.DateField(verbose_name='Дата выхода продукта на рынок'),
        ),
    ]
