# Generated by Django 4.2.9 on 2024-01-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_link', '0004_link_related_link_alter_link_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='debt',
            field=models.FloatField(blank=True, null=True, verbose_name='Задолженность перед поставщиком'),
        ),
    ]
